sudo: required

dist: xenial

services:
  - docker

language: python

python:
  - '3.6'

stages:
  - tests

cache: pip

jobs:

  include:

  - stage: test
    name: "Test Tango Master"
    install:
    - pip install -r test_requirements.txt
    script:
    - |
      docker run --rm -it \
        -v "$(pwd)":"$(pwd)":rw \
        -w "$(pwd)" \
        --entrypoint=./tools/run_test.sh \
        skasiid/tango_tests \
        tango_master -k test_master_device
    after_success:
    - codecov
    - coveralls

  - stage: test
    name: "Test SBI Config schema"
    install:
    - pip install -r test_requirements.txt
    - pip install jsonschema==2.6.0
    script:
    - |
      ./tools/run_test.sh \
      tango_master/src/tests/test_sbi_config_schema.py \
      --no-cov
